version: '3'

services:
  api:
    container_name: c2wk-api
    build: API
    ports:
    - 3000:3000
    env_file: .env
    depends_on:
      - db
    command: npm start

  db:
    container_name: c2wk-bd
    image: mysql:latest
    volumes:
      - c2wk-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    restart: always

  # front:
  #   container_name: c2wk-front
  #   build: Front/app
  #   ports:
  #   - 4200:4200
  #   environment:
  #   - API_HOST
  #   depends_on:
  #     - api
  #   command: npm start

volumes:
  c2wk-mysql-data: